OPS: Added github action to check for copyright in all Yoko files

diff --git a/.github/workflows/gradle.yml b/.github/workflows/gradle.yml
--- a/.github/workflows/gradle.yml
+++ b/.github/workflows/gradle.yml
@@ -23,6 +23,23 @@ jobs:
         distribution: 'adopt'
     - name: Grant execute permission for gradlew
       run: chmod +x gradlew
+    - name: Check for correct copyright in all Yoko files
+      run: |
+        SRC=$(find yoko*/ -name '*.java')
+        RC=0
+        echo "Checking copyright in Yoko src files..."
+        for filePath in $SRC; do
+          author=$(git log -1 --format="%an" $path)
+          if [[ $author != *"Alan"* ]]; then
+            if grep -Eq "Copyright ([[:digit:]]{4}?) IBM Corporation and " $filePath; then
+              echo "✅ Copyright OK: $filePath"
+            else
+              echo "❌ Copyright not found in $filePath"
+              RC=1
+            fi
+          fi
+        done
+        exit $RC
     - name: Check copyright Tag in Testify source files
       run: |
         SRC=$(find testify/ -name '*.java')
