OPS: Action for copyright tag in Testify source

diff --git a/.github/workflows/gradle.yml b/.github/workflows/gradle.yml
--- a/.github/workflows/gradle.yml
+++ b/.github/workflows/gradle.yml
@@ -23,6 +23,22 @@ jobs:
         distribution: 'adopt'
     - name: Grant execute permission for gradlew
       run: chmod +x gradlew
+    - name: Check copyright Tag in Testify source files
+      run: |
+        SRC=$(find yoko-testify/ -name '*.java')
+        export year_modified=`git log -n 1 --pretty=format:%cd --date=format:%Y $i`
+        RC=0
+        echo "Checking copyright"
+        for i in $SRC; do
+            if grep -Eq "Copyright ([[:digit:]]{4}, ?)?$year_modified IBM Corporation and " $i; then
+                echo "✅ Copyright ok: $i"
+            else
+                echo "❌ Copyright not found or incorrect year in $i"
+                echo "🔴 Last modification year should be: $year_modified"
+                RC=1
+            fi
+        done
+        exit $RC
     - name: Build with Gradle
       run: ./gradlew build
     - name: Upload test reports
